### ISSUE TITLE
项目启动失败

### ISSUE THREAD

**Issue by ccinoo** [ZainCheung/netease-cloud#103]
使用宝塔python项目管理器部署，已完成配置文件配置。部署完成后未启动，点击启动后报“项目启动失败”。
日志中看到如下报错：

`Traceback (most recent call last):
  File "/www/wwwroot/netease/main.py", line 25, in <module>
    logFile = open("run.log", encoding="utf-8", mode="a")
TypeError: 'encoding' is an invalid keyword argument for this function
Traceback (most recent call last):
  File "/www/wwwroot/netease/main.py", line 25, in <module>
    logFile = open("run.log", encoding="utf-8", mode="a")
TypeError: 'encoding' is an invalid keyword argument for this function`

**Comment by ccinoo** [comment]
使用宝塔面板“Python项目管理器”升级python版本至3.81后，启动项目报错如下：

`nohup: failed to run command ‘/www/wwwroot/netease-cloud/netease-cloud_venv/bin/python’: No such file or directory
nohup: failed to run command ‘/www/wwwroot/netease-cloud/netease-cloud_venv/bin/python’: No such file or directory
`

**Comment by ccinoo** [comment]
进入项目目录，手动创建环境后问题解决。
