### ISSUE TITLE
执行摘要测试失败

### ISSUE THREAD

**Issue by I-am-Refreshing-breeze** [ZainCheung/netease-cloud#112]
执行摘要测试失败
请求ID	
05373a1d-5f81-4289-be04-628b611a7a30
运行时间	
0ms
计费时间	
0ms
运行内存	
0.00MB
返回结果

Text
没有日志输出

执行日志
START RequestId:05373a1d-5f81-4289-be04-628b611a7a30

ERROR RequestId:05373a1d-5f81-4289-be04-628b611a7a30 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 160, in get_func_handler\n    return getattr(mod, fname)\nAttributeError: module 'index' has no attribute 'main_handler'","statusCode":443}

END RequestId:05373a1d-5f81-4289-be04-628b611a7a30

Report RequestId:05373a1d-5f81-4289-be04-628b611a7a30 Duration:0ms Memory:64MB MemUsage:0.000000MB

**Comment by JackChow6** [comment]
我也是这样
执行摘要测试失败
请求ID	
0dd03d21-b68e-4c4c-b442-4270bed842b8
运行时间	
3ms
运行内存	
16.63MB
返回结果

没有日志输出

执行日志
START RequestId:0dd03d21-b68e-4c4c-b442-4270bed842b8

ERROR RequestId:0dd03d21-b68e-4c4c-b442-4270bed842b8 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 331, in main\n    taskPool()\n  File \"/var/user/index.py\", line 308, in taskPool\n    config = init()\n  File \"/var/user/index.py\", line 256, in init\n    appToken = config['setting']['appToken']\n  File \"/var/lang/python3/lib/python3.6/configparser.py\", line 1233, in __getitem__\n    raise KeyError(key)\nKeyError: 'appToken'","statusCode":430}

END RequestId:0dd03d21-b68e-4c4c-b442-4270bed842b8

Report RequestId:0dd03d21-b68e-4c4c-b442-4270bed842b8 Duration:3ms Memory:64MB MemUsage:16.628906MB

**Comment by ZainCheung** [comment]
> 执行摘要测试失败
> 请求ID
> 05373a1d-5f81-4289-be04-628b611a7a30
> 运行时间
> 0ms
> 计费时间
> 0ms
> 运行内存
> 0.00MB
> 返回结果
> 
> Text
> 没有日志输出
> 
> 执行日志
> START RequestId:05373a1d-5f81-4289-be04-628b611a7a30
> 
> ERROR RequestId:05373a1d-5f81-4289-be04-628b611a7a30 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n File "/var/runtime/python3/bootstrap.py", line 133, in init_handler\n func_handler = get_func_handler(file.rsplit(".", 1)[0], func)\n File "/var/runtime/python3/bootstrap.py", line 160, in get_func_handler\n return getattr(mod, fname)\nAttributeError: module 'index' has no attribute 'main_handler'","statusCode":443}
> 
> END RequestId:05373a1d-5f81-4289-be04-628b611a7a30
> 
> Report RequestId:05373a1d-5f81-4289-be04-628b611a7a30 Duration:0ms Memory:64MB MemUsage:0.000000MB

关键日志：module 'index' has no attribute 'main_handler'
错误原因：没有找到`main_handler`，教程里写到要在部署的时候将`index.main_handler`改为`index.main`
详情查看：[云函数部署](https://zaincheung.github.io/netease-cloud/#/python/cloud?id=_3-%e4%b8%8a%e4%bc%a0%e4%bb%a3%e7%a0%81)

**Comment by ZainCheung** [comment]
> 我也是这样
> 执行摘要测试失败
> 请求ID
> 0dd03d21-b68e-4c4c-b442-4270bed842b8
> 运行时间
> 3ms
> 运行内存
> 16.63MB
> 返回结果
> 
> 没有日志输出
> 
> 执行日志
> START RequestId:0dd03d21-b68e-4c4c-b442-4270bed842b8
> 
> ERROR RequestId:0dd03d21-b68e-4c4c-b442-4270bed842b8 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n File "/var/user/index.py", line 331, in main\n taskPool()\n File "/var/user/index.py", line 308, in taskPool\n config = init()\n File "/var/user/index.py", line 256, in init\n appToken = config['setting']['appToken']\n File "/var/lang/python3/lib/python3.6/configparser.py", line 1233, in **getitem**\n raise KeyError(key)\nKeyError: 'appToken'","statusCode":430}
> 
> END RequestId:0dd03d21-b68e-4c4c-b442-4270bed842b8
> 
> Report RequestId:0dd03d21-b68e-4c4c-b442-4270bed842b8 Duration:3ms Memory:64MB MemUsage:16.628906MB

关键日志： line 256, in init\n appToken = config['setting']['appToken']
错误原因：解析配置文件时没有找到`appToken`，建议审查自己的配置文件`init.config`里有没有该项，如果没有请拉取最新的代码，有的话检查配置文件格式是否存在问题
详情查看：[任务推送](https://zaincheung.github.io/netease-cloud/#/config/?id=%e4%bb%bb%e5%8a%a1%e6%8e%a8%e9%80%81)

**Comment by JackChow6** [comment]
好像没有App token

**Comment by JackChow6** [comment]
![20210822021105(1).png](https://user-images.githubusercontent.com/89273213/130331240-e746f5c6-bff8-42ae-9de3-8184ab8fc927.png)可以了可以了，用电脑就很快
