### ISSUE TITLE
部署完日志报错

### ISSUE THREAD

**Issue by cat-kun** [ZainCheung/netease-cloud#143]
START RequestId: cb995243-6135-46de-aba4-07375894c57d

Init Report RequestId: cb995243-6135-46de-aba4-07375894c57d Coldstart: 236ms (PullCode: 64ms InitRuntime: 5ms InitFunction: 167ms) Memory: 512MB MemUsage: 8.47MB

ERROR RequestId: cb995243-6135-46de-aba4-07375894c57d Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python37/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python37/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python37/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python37/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 728, in exec_module   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed   File "/var/user/index.py", line 11, in <module>     import requests ModuleNotFoundError: No module named 'requests'", "statusCode": 443}

END RequestId: cb995243-6135-46de-aba4-07375894c57d

Report RequestId: cb995243-6135-46de-aba4-07375894c57d Duration: 0ms Memory: 512MB MemUsage: 8.47MB

START RequestId:cb995243-6135-46de-aba4-07375894c57d

ERROR RequestId:cb995243-6135-46de-aba4-07375894c57d Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python37/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python37/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python37/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python37/lib/python3.7/imp.py\", line 171, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 696, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 677, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 728, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 219, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 11, in \u003cmodule\u003e\n    import requests\nModuleNotFoundError: No module named 'requests'","statusCode":443}

END RequestId:cb995243-6135-46de-aba4-07375894c57d

Report RequestId:cb995243-6135-46de-aba4-07375894c57d Duration:0ms Memory:512MB MemUsage:0.000000MB

**Comment by cat-kun** [comment]
解决了，python环境必须使用3.6版本
