### ISSUE TITLE
本地部署运行报错

### ISSUE THREAD

**Issue by xiaoicx** [ZainCheung/netease-cloud#81]
环境 python3.7.2  pip3  centos7  阿里云源

报错如下: 经测试在腾讯云使用宝塔部署出现同样的错误 经过手动编译python替换为默认python版本错误一致

[root@master-node netease-cloud]# python main.py 
配置文件读取完毕
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 1158, in run
    self.function(*self.args, **self.kwargs)
  File "main.py", line 283, in taskPool
    check() # 每天对api做一次检查
  File "main.py", line 269, in check
    respones = requests.get(url)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/sessions.py", line 510, in request
    prep = self.prepare_request(req)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/sessions.py", line 453, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/python3/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '?do=check': No schema supplied. Perhaps you meant http://?do=check?

**Comment by ShenHai9** [comment]
这个问题 请问有在init.config文件中配置正确的apiurl地址吗

`
[setting]
# 接口API，开关的选项只有 True 和 False
# 如需使用本项目还请自行部署API，地址：https://github.com/ZainCheung/netease-cloud-api
api = 
`

希望可以帮到你。
